name: Vercel Preview Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
    push:
        branches-ignore:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Load & Cache Dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

    lint-check:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Run Lint
              run: npm run lint

    format-check:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Run Prettier:Check
              run: npm run prettier:check

    test:
        runs-on: ubuntu-latest
        needs: [lint-check, format-check]
        steps:
            - name: Run Tests
              run: npm run test

    deploy-preview:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ env.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --token=${{ env.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }}
